"""Server-side i18n.

Mirrors the strings needed for SEO-critical content in the templates (titles,
descriptions, navigation labels) so that crawlers see fully translated pages
without waiting for JavaScript.

Keep keys in sync with `frontend/js/i18n.js` where they overlap.
"""

from __future__ import annotations

SUPPORTED_LANGS = ("en", "fr")
DEFAULT_LANG = "en"

LANG_NAMES = {"en": "English", "fr": "Français"}
LANG_LOCALES = {"en": "en_US", "fr": "fr_FR"}

STRINGS: dict[str, dict[str, str]] = {
    "site_name": {
        "en": "UpToCure",
        "fr": "UpToCure",
    },
    "site_tagline": {
        "en": "Rare disease research, made accessible",
        "fr": "La recherche sur les maladies rares, accessible à tous",
    },
    "site_description": {
        "en": "UpToCure is a free, open-source hub of up-to-date research summaries on rare diseases. Each report cites peer-reviewed publications, clinical trials, and leading institutions.",
        "fr": "UpToCure est un portail libre et open source de synthèses de recherche actualisées sur les maladies rares. Chaque rapport cite des publications évaluées par les pairs, des essais cliniques et les institutions de référence.",
    },
    "home_title": {
        "en": "UpToCure — Rare Disease Research Hub",
        "fr": "UpToCure — Centre d'information sur la recherche sur les maladies rares",
    },
    "home_h1": {
        "en": "Source-linked research on rare diseases",
        "fr": "La recherche sur les maladies rares, avec ses sources",
    },
    "home_intro": {
        "en": "{count} living summaries of peer-reviewed research, clinical trials, and emerging therapies — written to be read, and always linked back to the original papers.",
        "fr": "{count} synthèses vivantes de la recherche évaluée par les pairs, des essais cliniques et des thérapies émergentes — à lire, et toujours reliées aux publications d’origine.",
    },
    "featured_heading": {
        "en": "Recently updated",
        "fr": "Mis à jour récemment",
    },
    "browse_heading": {
        "en": "Browse all reports",
        "fr": "Parcourir tous les rapports",
    },
    "browse_filter_placeholder": {
        "en": "Filter by disease name…",
        "fr": "Filtrer par nom de maladie…",
    },
    "browse_jump_label": {
        "en": "Jump to letter",
        "fr": "Aller à la lettre",
    },
    "trust_banner": {
        "en": "AI-generated summaries. Verify every claim with the cited sources before acting on them.",
        "fr": "Synthèses générées par IA. Vérifiez chaque affirmation auprès des sources citées avant d’agir.",
    },
    "all_reports_heading": {
        "en": "All disease reports",
        "fr": "Tous les rapports",
    },
    "search_placeholder": {
        "en": "Search by disease name…",
        "fr": "Rechercher une maladie…",
    },
    "nav_methodology": {
        "en": "Methodology",
        "fr": "Méthodologie",
    },
    "skip_to_content": {
        "en": "Skip to content",
        "fr": "Aller au contenu",
    },
    "search_title": {
        "en": "Search rare disease reports",
        "fr": "Rechercher des rapports sur les maladies rares",
    },
    "search_results_for": {
        "en": "Results for “{query}”",
        "fr": "Résultats pour « {query} »",
    },
    "search_no_results": {
        "en": "No reports match your query yet. Try a broader keyword or request a new report below.",
        "fr": "Aucun rapport ne correspond à votre recherche. Essayez un mot-clé plus large ou demandez un nouveau rapport ci-dessous.",
    },
    "report_back": {
        "en": "← Back to all reports",
        "fr": "← Retour à tous les rapports",
    },
    "report_meta_published": {
        "en": "Last updated",
        "fr": "Mis à jour le",
    },
    "badge_updated": {
        "en": "Recently updated",
        "fr": "Mis à jour récemment",
    },
    "report_meta_model": {
        "en": "Generated by",
        "fr": "Généré par",
    },
    "report_related": {
        "en": "More disease reports",
        "fr": "Plus de rapports",
    },
    "report_language_alt": {
        "en": "Also available in",
        "fr": "Disponible également en",
    },
    "request_report_cta": {
        "en": "Don't see your disease? Request a report",
        "fr": "Votre maladie n'apparaît pas ? Demandez un rapport",
    },
    "disclaimer": {
        "en": "Reports are generated by an AI agent and may contain inaccuracies. Always verify with the cited sources and consult a healthcare professional for medical decisions.",
        "fr": "Les rapports sont générés par un agent IA et peuvent contenir des inexactitudes. Vérifiez toujours auprès des sources citées et consultez un professionnel de santé pour toute décision médicale.",
    },
    "methodology_link": {
        "en": "Read our methodology",
        "fr": "Lire notre méthodologie",
    },
    "not_found_title": {
        "en": "Page not found",
        "fr": "Page introuvable",
    },
    "not_found_body": {
        "en": "The page you are looking for does not exist or has moved.",
        "fr": "La page que vous cherchez n'existe pas ou a été déplacée.",
    },
    "footer_copyright": {
        "en": "© Yannis Tevissen — Open-source on GitHub",
        "fr": "© Yannis Tevissen — Open source sur GitHub",
    },
    "nav_language": {
        "en": "Language",
        "fr": "Langue",
    },
}


def normalise_lang(lang: str | None) -> str:
    if not lang:
        return DEFAULT_LANG
    code = lang.lower().split("-")[0]
    return code if code in SUPPORTED_LANGS else DEFAULT_LANG


def t(key: str, lang: str, **kwargs) -> str:
    entry = STRINGS.get(key, {})
    text = entry.get(lang) or entry.get(DEFAULT_LANG) or key
    return text.format(**kwargs) if kwargs else text
