name: Deploy UpToCure

on:
  push:
    branches:
      - main  # Adjust if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          eval "$(ssh-agent -s)"
          ssh-add private_key
          ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST << 'EOF'
            cd /home/ubuntu/UpToCure/UpToCure
            git pull origin main
            pdm install
            sudo systemctl restart uptocure
          EOF